; =====================================================================================
;  Odyssey-10 Pro -- Ground Station Bridge (ESP32 + SX1278)
; =====================================================================================
[env:odyssey-gcs]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200

build_flags =
    -I ../../shared
    -std=gnu++17
    -Wall
    -Wextra

build_unflags = -std=gnu++11

lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
